/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package adventofcode2022

import adventofcode2022.day11.solutionDay11Part1
import adventofcode2022.day11.solutionDay11Part2

fun main() {
    solutionDay11Part1()
    solutionDay11Part2()
}
