/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package adventofcode2022

import adventofcode2022.day15.solutionDay15Part1
import adventofcode2022.day15.solutionDay15Part2

fun main() {
    solutionDay15Part1(2000000)
    solutionDay15Part2(4000000)
}
