/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package adventofcode2022

import adventofcode2022.day09.solutionDay09Part1
import adventofcode2022.day09.solutionDay09Part2

fun main() {
    solutionDay09Part1()
    solutionDay09Part2()
}
