/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package adventofcode2022

import kotlin.test.Test
import kotlin.test.assertTrue

class AppTest {
    @Test fun day01() {
        assertTrue { true }
    }
}
